# Generated by Django 4.0.4 on 2022-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('publish_year', models.DateField(max_length=10)),
                ('img', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
