# Generated by Django 4.0.4 on 2022-07-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_year',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=50),
        ),
    ]
